### ISSUE TITLE
Resolver TODO: Sobre Facebook na Etapa Mediana

### ISSUE THREAD

**Issue by JPTIZ** [seccom-ufsc/manual#7]
Resolver TODO em um arquivo existente
-------------------------------------

- **Arquivo**: [3. Etapa Mediana](https://github.com/seccom-ufsc/manual/wiki/3.-Etapa-Mediana)

- **Local**: Facebook

- **O que fazer**: Descrever como lidar com facebook:
  - [ ] Sobre falar com quem estava na página no ano anterior;
  - [ ] Quando postar, como postar;
  - [ ] Programas para utilizar (Inkscape).

**Comment by JPTIZ** [comment]
[Resolvido via revisão](https://github.com/seccom-ufsc/manual/wiki/3.-Etapa-Mediana/4bd9e54379009927ab496a19db745ad85eb49921).
