### ISSUE TITLE
Adicionar ao manual: Incrementar checklist com SECCOM 2019

### ISSUE THREAD

**Issue by JPTIZ** [seccom-ufsc/manual#8]
Tipo de adição:
---------------

- [ ] Criar arquivo no manual.
- [x] Adicionar seção/subseção a algum arquivo existente.

Conteúdo
--------

Na **Etapa "A Semana"**, incrementar checklist com os itens da SECCOM 2019.

**Comment by JPTIZ** [comment]
Parte foi feita: https://github.com/seccom-ufsc/manual/wiki/5.-Instru%C3%A7%C3%B5es-para-a-Semana/df305f18eca71c0da65cf2a7b75d06428c1444ce

Falta ver se o @Coquinho quer adicionar mais algo.

**Comment by Coquinho** [comment]
O que vem a cabeça são só algumas pequenas sugestões:
(Eu tb dei um `sort` na list, embora por algum motivo `Água` vá para o final)
```diff
diff --git a/ori b/ori
index c808e62..2e94428 100644
--- a/ori
+++ b/ori
@@ -4,10 +4,10 @@ SECCOM - Instruções para a Semana
 Sobre
 -----
 
-Aqui estão listadas algumas necessidades básicas que devem ser preparadas
-na semana anterior ao evento. Tenha em mente que aqui pode não estar anotado
-todo o necessário para uma edição específica da SECCOM, então use apenas como
-guia e não como uma lista atual.
+Aqui estão listadas algumas necessidades básicas que devem ser preparadas na
+semana anterior ao evento. Tenha em mente que aqui pode tanto não estar anotado
+todo o necessário, quanto até ter coisas desnecessárias para uma edição
+específica da SECCOM, então use apenas como guia e não como uma lista atual.
 
 Checklist
 ---------
@@ -20,23 +20,26 @@ issue](https://gitlab.com/petcomp-ufsc/manual_petcomp/issues/new) entitulada
 
  - [ ] Discurso de abertura do evento
  - [ ] Discurso de encerramento do evento
- - [ ] Textos de abertura das atividades acadêmicas
  - [ ] Material de apoio da atividade (i.e. Perguntas da mesa redonda)
  - [ ] Microfone
+ - [ ] Passador de Slides
+ - [ ] Projetor
  - [ ] Som
+ - [ ] Textos de abertura de cada atividade acadêmica
  - [ ] Água para os palestrantes
- - [ ] Passador de Slides
 
 ### Minicursos
 
- - [ ] Água para os ministrantes
- - [ ] Adaptador VGA-HDMI
+ - [ ] Adaptador HDMI-VGA
  - [ ] Adaptador de tomada/T/"Benjamim" (3 pinos -> 2 pinos)
+ - [ ] Teste dos softwares necessários
+ - [ ] Água para os ministrantes
 
 ### Coffee-Break
 
- - [ ] Mesa (para a hora do Coffee)
  - [ ] Cafeteira
- - [ ] Reservatório para o café (recomendado ter 2)
- - [ ] Pratos para os salgadinhos
  - [ ] Copos
+ - [ ] Mesa
+ - [ ] Pratos para a comida
+ - [ ] Reservatório para o café (recomendado ter 2)
+ - [ ] Utensilios de limpeza (Vassoura, pá, possivelmente sacos de lixo)
```

A maior parte das minhas sugestões é questão de explicitar de mais/menoes alguma coisa, então pode passar tua régua e ver como fica melhor.

**Comment by JPTIZ** [comment]
> (Eu tb dei um `sort` na list, embora por algum motivo `Água` vá para o final)

Provavelmente a comparação é só `char < char` seguindo a codificação de caracteres, e nesse caso `Á` tem valor 193 e `A` é 65, tanto que "Adaptador **d**e tomada" ficou depois de "Adaptador **H**DMI", porque maiúsculas tem valor menor que minúsculas (A-Z = 65-90, a-z = 97-122).

**Comment by JPTIZ** [comment]
Feito: https://github.com/seccom-ufsc/manual/wiki/5.-Instru%C3%A7%C3%B5es-para-a-Semana/80e9268a105564a33ee75eb6c52b0d54dfb190c0
